name: Actions Loki Fundamentals

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to cut a release from'
        required: false
        type: string
        default: ''
      release_tag_name:
        description: 'The name to tag the controller image with'
        required: true
        type: string
        default: '1.0.0'
      push_to_registries:
        description: 'Push images to registries'
        required: true
        type: boolean
        default: true
      publish_loki_fundamentals:
        description: 'Publish Loki Fundametals'
        required: true
        type: boolean
        default: true

env:
  HELM_VERSION: v3.8.0

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"

  Build-Push-Image:
    name: Build and push controller image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            # If inputs.ref is empty, it'll resolve to the default branch
            ref: ${{ inputs.ref }}

      - name: Resolve parameters
        id: resolve_parameters
        run: |
              resolvedRef="${{ inputs.ref }}"
              if [ -z "$resolvedRef" ]
              then
                resolvedRef="${{ github.ref }}"
              fi
              echo "resolved_ref=$resolvedRef" >> $GITHUB_OUTPUT
              echo "INFO: Resolving short SHA for $resolvedRef"
              echo "short_sha=$(git rev-parse --short $resolvedRef)" >> $GITHUB_OUTPUT
              echo "INFO: Normalizing repository name (lowercase)"
              echo "repository_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Pinning v0.9.1 for Buildx and BuildKit v0.10.6
          # BuildKit v0.11 which has a bug causing intermittent
          # failures pushing images to GHCR
          version: v0.9.1
          driver-opts: image=moby/buildkit:v0.10.6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push controller image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ inputs.release_tag_name }}
          push: ${{ inputs.push_to_registries }}
          tags: |
            ghcr.io/${{ steps.resolve_parameters.outputs.repository_owner }}/loki-fundamentals:${{ inputs.release_tag_name }}
            ghcr.io/${{ steps.resolve_parameters.outputs.repository_owner }}/loki-fundamentals:${{ inputs.release_tag_name }}-${{ steps.resolve_parameters.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Job summary
        run: |
            echo "The [loki-fundamentals](https://github.com/nicoas/loki-fundamentals/blob/main/.github/workflows/github-actions.yaml) workflow run was completed successfully!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Parameters:**" >> $GITHUB_STEP_SUMMARY
            echo "- Ref: ${{ steps.resolve_parameters.outputs.resolvedRef }}" >> $GITHUB_STEP_SUMMARY
            echo "- Short SHA: ${{ steps.resolve_parameters.outputs.short_sha }}" >> $GITHUB_STEP_SUMMARY
            echo "- Release tag: ${{ inputs.release_tag_name }}" >> $GITHUB_STEP_SUMMARY
            echo "- Push to registries: ${{ inputs.push_to_registries }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY        

  Publish-Helm-Oci-Loki-Fundamentals:
            if: ${{ inputs.publish_loki_fundamentals == true }}
            needs: Build-Push-Image
            name: Publish Helm Chart for Loki Fundamentals
            runs-on: ubuntu-latest
            steps:
              - name: Checkout
                uses: actions/checkout@v4
                with:
                  # If inputs.ref is empty, it'll resolve to the default branch
                  ref: ${{ inputs.ref }}
        
              - name: Resolve parameters
                id: resolve_parameters
                run: |
                  resolvedRef="${{ inputs.ref }}"
                  if [ -z "$resolvedRef" ]
                  then
                    resolvedRef="${{ github.ref }}"
                  fi
                  echo "INFO: Resolving short SHA for $resolvedRef"
                  echo "short_sha=$(git rev-parse --short $resolvedRef)" >> $GITHUB_OUTPUT
                  echo "INFO: Normalizing repository name (lowercase)"
                  echo "repository_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        
              - name: Set up Helm
                # Using https://github.com/Azure/setup-helm/releases/tag/v4.2
                uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814
                with:
                  version: ${{ env.HELM_VERSION }}

              - name: Publish new helm chart for loki-fundamentals
                run: |
                    echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
                    LOKI_FUNDAMENTALS_CHART_VERSION_TAG=$(cat chart/Chart.yaml | grep version: | cut -d " " -f 2)
                    echo "LOKI_FUNDAMENTALS_CHART_VERSION_TAG=${LOKI_FUNDAMENTALS_CHART_VERSION_TAG}" >> $GITHUB_ENV
                    helm package chart --version="${LOKI_FUNDAMENTALS_CHART_VERSION_TAG}"
                    helm push loki-fundamentals-"${LOKI_FUNDAMENTALS_CHART_VERSION_TAG}".tgz oci://ghcr.io/${{ steps.resolve_parameters.outputs.repository_owner }}/loki-fundamentals-chart
          
              - name: Job summary
                run: |
                    echo "New helm chart for loki-fundamentals published successfully!" >> $GITHUB_STEP_SUMMARY
                    echo "" >> $GITHUB_STEP_SUMMARY
                    echo "**Parameters:**" >> $GITHUB_STEP_SUMMARY
                    echo "- Ref: ${{ steps.resolve_parameters.outputs.resolvedRef }}" >> $GITHUB_STEP_SUMMARY
                    echo "- Short SHA: ${{ steps.resolve_parameters.outputs.short_sha }}" >> $GITHUB_STEP_SUMMARY
                    echo "- loki-fundamentals Chart version: ${{ env.LOKI_FUNDAMENTALS_CHART_VERSION_TAG }}" >> $GITHUB_STEP_SUMMARY


